### ISSUE TITLE
"Chrome" on iPad 2 is detected as "Safari"

### ISSUE THREAD

**Issue by pastinepolenta** [srfrnk/ng-device-detector#10]
"Chrome" on iPad 2 is detected as "Safari"

**Comment by oliverbestmann** [comment]
"Chrome" is detected correctly on iOS now, but the version is not correctly identified. The current user agent string is `Mozilla/5.0 (iPhone; CPU iPhone OS 9_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/47.0.2526.107 Mobile/13C75 Safari/601.1.46`, the version returned is then `0`. It should return version `47.0.2526.107`.
