### ISSUE TITLE
Doesn't have a minified JS version

### ISSUE THREAD

**Issue by srfrnk** [srfrnk/ng-device-detector#16]

**Comment by christianfeurer** [comment]
When is next release planned. I'm very interested in using this minified version :+1:

**Comment by srfrnk** [comment]
Sorry, I didn't realize you were waiting for a release when I committed the changes.
I'll pack a release today.

**Comment by srfrnk** [comment]
Done. As well as updated npm and bower repos. Tell me if there's a problem still.

**Comment by christianfeurer** [comment]
I was putting this into my app by using bower. So the new version works great now. Thank you very much! :+1:
