### ISSUE TITLE
add IE11 browser detection regex

### ISSUE THREAD

**Issue by qpitlove** [srfrnk/ng-device-detector#21]
IE11 has 'Trient' instead of 'MSIE' in navigator.userAgent string.
so I want to merge this PR
https://github.com/srfrnk/ng-device-detector/pull/20

BUT I can't fixed BROWSER_VERSIONS_RE_MAP when Brower IE Trient version.

Could you check is also?

**Comment by qpitlove** [comment]
Hi! @srfrnk 
I add IE11 in my local machine Test case and request PR
https://github.com/srfrnk/ng-device-detector/pull/22

BUT a Point of concern is that modified BROWSER_VERSION_RE_MAP in ng-device-detector.js
each Map value was regex, except IE has array
I'm not sure whether is correct~

Thanks you

**Comment by derekmooney** [comment]
Can you create a tag for this? I'm trying to pull in 1.1.2 via bower but getting an error that the version isn't available (since there isn't a tag for it).

**Comment by srfrnk** [comment]
@derekmooney  - Give it a try now please... LMK if you've still got a problem.

**Comment by derekmooney** [comment]
Yeah, all good, thanks!
