### ISSUE TITLE
I can't install lastest source from bower install

### ISSUE THREAD

**Issue by qpitlove** [srfrnk/ng-device-detector#23]
I've added checking IE11 Trient version, but when I bower install, previous version is downloaded.
I think you need to clear bower cache forcely or bower version up.

Could you check this issue?

**Comment by srfrnk** [comment]
bower takes the version from npm - i need to publish npm for it to work.
after the merges i will run it.
also please make sure you run gulp - to update the minified version before committing.

**Comment by qpitlove** [comment]
Ok i appiled minified version also to PR
thanks

**Comment by srfrnk** [comment]
Hi @qpitlove - is it working for you now?

**Comment by qpitlove** [comment]
I'm sorry to late for your question~
I'll check it and tell you~
Thanks

**Comment by qpitlove** [comment]
now it's working for me !!
something like
```
Using classes:


 os-windows 











 browser-ie 








{"raw":{"userAgent":"Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; rv:11.0) like Gecko","os":{"windows":true,"mac":false,"ios":false,"android":false,"linux":false,"unix":false,"firefoxos":false,"windows-phone":false,"ps4":false,"vita":false,"unknown":false},"browser":{"chrome":false,"firefox":false,"safari":false,"opera":false,"ie":true,"ps4":false,"vita":false,"unknown":false},"device":{"android":false,"ipad":false,"iphone":false,"ipod":false,"blackberry":false,"firefoxos":false,"windows-phone":false,"ps4":false,"vita":false,"unknown":false},"os_version":{"windows-3-11":false,"windows-95":false,"windows-me":false,"windows-98":false,"windows-ce":false,"windows-2000":false,"windows-xp":false,"windows-server-2003":false,"windows-vista":false,"windows-7":true,"windows-8-1":false,"windows-8":false,"windows-nt-4-0":true,"unknown":false}},"os":"windows","browser":"ie","device":"unknown","os_version":"windows-7","browser_version":"11.0"}
```
device is unkown, because  it's not desktop os. is it right ?

**Comment by srfrnk** [comment]
I'm not sure what device it is myself... where are you running it? What kind of hardware is it?

**Comment by qpitlove** [comment]
i have window-7 and ie 11 and running it.
i dig it, and found device has something like this list
'''
deviceInfo.device = [
                    DEVICES.ANDROID,
                    DEVICES.IPAD,
                    DEVICES.IPHONE,
                    DEVICES.IPOD,
                    DEVICES.BLACKBERRY,
                    DEVICES.FIREFOXOS,
                    DEVICES.WINDOWSPHONE,
                    DEVICES.PS4,
                    DEVICES.VITA
                ]
'''

**Comment by srfrnk** [comment]
for desktop the device should be unknown. that's ok.

**Comment by qpitlove** [comment]
I got it.
thanks
