### ISSUE TITLE
Opera 15+ browser detected as Chrome

### ISSUE THREAD

**Issue by imjustd** [srfrnk/ng-device-detector#24]
I know that Opera from version 15 is practically a Chrome clone, so it is detected as Chrome. But I think it would be nice if it is detected as Opera and the its right version.

**Comment by srfrnk** [comment]
can you send me the user agent it generates? - maybe I can distinguish between the two...

**Comment by imjustd** [comment]
The current user agent is:
`Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36 OPR/29.0.1795.47`

If you notice at the end there is `OPR/29.0.1795.47` so you can check `OPR` for Opera v15+ and the number after that for version
