### ISSUE TITLE
plz update bower repository for re-tree dependency

### ISSUE THREAD

**Issue by qpitlove** [srfrnk/ng-device-detector#26]
HI. I just replied that PR is merged.
but I can't install re-tree module by bower install command because bower repository doesn't apply it

plz check this it~

thanks

**Comment by srfrnk** [comment]
I just ran 'bower i' and got this:
```
shahar@shahar-laptop:~/sources/ng-device-detector$ bower i
bower not-cached    git://github.com/srfrnk/re-tree.git#>=0.0.2
bower resolve       git://github.com/srfrnk/re-tree.git#>=0.0.2
bower download      https://github.com/srfrnk/re-tree/archive/v0.0.2.tar.gz
bower extract       re-tree#>=0.0.2 archive.tar.gz
bower resolved      git://github.com/srfrnk/re-tree.git#0.0.2
bower install       re-tree#0.0.2

re-tree#0.0.2 bower_components/re-tree
```

Can you tell me what happens when you try it?

**Comment by qpitlove** [comment]
I also just run and got this
```
mongmong-nhnent:client irteam$ bower i
bower ng-device-detector#~1.1.4 cached git://github.com/srfrnk/ng-device-detector.git#1.1.4
bower ng-device-detector#~1.1.4         validate 1.1.4 against git://github.com/srfrnk/ng-device-detector.git#~1.1.4
bower es5-shim                  extra-resolution Unnecessary resolution: es5-shim#4.0.3
bower bootstrap-select          extra-resolution Unnecessary resolution: bootstrap-select#1.6.4
bower ng-device-detector#~1.1.4          install ng-device-detector#1.1.4

ng-device-detector#1.1.4 app/bower_components/ng-device-detector
```

why is different ? 
I defined only ng-device-detect#1.1.4 module in bower.json

**Comment by srfrnk** [comment]
maybe try:
bower cache clean

and if that doesn't work perhaps updating bower might help:
sudo npm up -g bower

does any of these work?

**Comment by qpitlove** [comment]
it's not work for me that apply cache clean and npm update bower( previous and lastest is 1.4.1).

thanks for your support~

**Comment by srfrnk** [comment]
i think it might be that the bower repository didn't update.
i created a new git release and published to npm.
it still seems that bower isn't updated but it may take a few hours for them to pick it up.
please try in the next few hours and let's see if it updates correctly.
i'll keep an eye on bower myself....
in any case please update me when you manage to get it updated. 10x.

**Comment by qpitlove** [comment]
ok~ got it. thanks

**Comment by srfrnk** [comment]
actually i think they depend on the git releases but who knows :)
so it's ok now - can i close the issue?

**Comment by qpitlove** [comment]
ok. got it
