### ISSUE TITLE
Windows 10.0 detected like Windows NT 4.0

### ISSUE THREAD

**Issue by imjustd** [srfrnk/ng-device-detector#27]
Although Windows 10 is not officially released there are preview builds with the new user agent:

`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0`

and for Windows Phone:

`Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; DEVICE INFO) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Mobile Safari/537.36 Edge/12.0`

You can simply detect them with `Windows NT 10.0` and `Windows Phone 10.0`

Here're more details: https://msdn.microsoft.com/en-us/library/hh869301%28v=vs.85%29.aspx

**Comment by srfrnk** [comment]
hi @imjustd ,
Can you tell me what browser do these UAs represent?
10x.
