### ISSUE TITLE
Inject in a config

### ISSUE THREAD

**Issue by michelem09** [srfrnk/ng-device-detector#28]
Hello,
I'm trying to inject the deviceDetector in a config section like so:

    angular.module('core', ['devideDetector']).config(
    	    function (devideDetector) {
    		    console.log(devideDetector);
    	    }
    );

But it throws me an error, can you help me?
Thanks

**Comment by srfrnk** [comment]
Hi,

Sure.... Can you send the error message? Maybe create a plunker or fiddle?

Yours,
Shahar.

**Comment by michelem09** [comment]
Here is: http://embed.plnkr.co/Bon5Ueq33cLGyj92aAUm/preview

Problem, I read, you can't inject factory or service into config, but only provider, so I tried also this, but I think I'm missing something

    angular.module('core', ['devideDetectorProvider']).config(
        function (devideDetectorProvider) {
            console.log(devideDetectorProvider);
        }
    );

**Comment by srfrnk** [comment]
So basically you should use this code instead:
```
app.config(
  ["deviceDetectorProvider",function (deviceDetector) {
      console.log(deviceDetector); 
  }]
);
```

Forked your plunker - got it to work - please see:
http://plnkr.co/edit/HiFzlxeAyyiihVMzcj1S?p=preview

Hope that helps,
Shahar.

**Comment by jayzeng** [comment]
I am trying to do the same thing, that I need to perform logic to set a mobile flag base on user browser, in the config block. 

I am confused how your plunker works as provider is not defined in the module, coping 
```
app.config(
  ["deviceDetectorProvider",function (deviceDetector) {
      console.log(deviceDetector); 
  }]
);
```
doesn't inject the deviceDetector instance correctly, did I miss anything?

**Comment by srfrnk** [comment]
the code injects the provider correctly.
if you need a service instance then config is not the place to do it.
if you can explain your scenario i may be able to suggest a solution.
