### ISSUE TITLE
Error in latest version, 1.1.7

### ISSUE THREAD

**Issue by freshp86** [srfrnk/ng-device-detector#30]
Getting the following error in the latest version.

Error: [$injector:modulerr] Failed to instantiate module ng.deviceDetector due to:
Error: [$injector:modulerr] Failed to instantiate module reTree due to:
Error: [$injector:nomod] Module 'reTree' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Last version that was working for me was 1.1.2.
Does the new version require including reTree myself, on top of ng-device-detector.min.js?

**Comment by srfrnk** [comment]
hi,
you're right.
if you run 'npm i' / 'bower i' you'll see re-tree added.
then you should add the re-tree.js just before ng-device-detector.js is loaded.
you can see the plunker at http://plnkr.co/edit/urqMI1?p=preview
hope that helps,
Shahar
