### ISSUE TITLE
Use SemVer

### ISSUE THREAD

**Issue by matiassingers** [srfrnk/ng-device-detector#31]
Release [`v1.1.4`](https://github.com/srfrnk/ng-device-detector/releases/tag/v1.1.4) breaks backwards compatibility because people now needs to inject re-tree.js as well.

So if people had the following in their `bower.json`, suddenly it'll just break on next install:
```json
"dependencies": {
  "ng-device-detector": "~1.1.3"
}
```

See [Semantic Versioning](http://semver.org/) for more info.

**Comment by srfrnk** [comment]
You are correct - please run:
$ bower i

Then add the following to your HTML:
<script type="text/javascript" src=".../re-tree.js"></script>
<script type="text/javascript" src=".../ng-device-detector.js"></script>

10x.

**Comment by matiassingers** [comment]
I fixed the issue quite easily.

But maybe you should bump the major or minor version as well to avoid others facing this issue - this will break any new deployments/builds.

**Comment by srfrnk** [comment]
I don't think I can do anything in retrospect since the version is already out. Next time I have a breaking change I will try to remember this valuable insight :)
