### ISSUE TITLE
Windows phone reports as os-ios, browser-safari, device-iphone

### ISSUE THREAD

**Issue by vinaynaidu** [srfrnk/ng-device-detector#32]
Tested from Lumia 930.

`{{deviceDetector}}` outputs: 

    {  
      "raw":{  
         "userAgent":"Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 930) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537",
         "os":{  
            "windows":false,
            "mac":true,
            "ios":true,
            "android":true,
            "linux":false,
            "unix":false,
            "firefoxos":false,
            "windows-phone":true,
            "ps4":false,
            "vita":false,
            "unknown":false
         },
         "browser":{  
            "chrome":false,
            "firefox":false,
            "safari":true,
            "opera":false,
            "ie":true,
            "ps4":false,
            "vita":false,
            "unknown":false
         },
         "device":{  
            "android":true,
            "ipad":false,
            "iphone":true,
            "ipod":false,
            "blackberry":false,
            "firefoxos":false,
            "windows-phone":true,
            "ps4":false,
            "vita":false,
            "unknown":false
         },
         "os_version":{  
            "windows-3-11":false,
            "windows-95":false,
            "windows-me":false,
            "windows-98":false,
            "windows-ce":false,
            "windows-2000":false,
            "windows-xp":false,
            "windows-server-2003":false,
            "windows-vista":false,
            "windows-7":false,
            "windows-8-1":false,
            "windows-8":false,
            "windows-nt-4-0":false,
            "unknown":false
         }
      },
      "os":"ios",
      "browser":"safari",
      "device":"android",
      "os_version":"unknown",
      "browser_version":"0"
    }

I'm going to work on a PR in a bit, on an initial glance, looks like the string `like iPhone...` in raw string might be messing with the regex. (I could be completely wrong though)

**Comment by srfrnk** [comment]
Yea - it's ******* microsoft - they just have to put every known keyword in the UA....
I think best solution is to add a {not:"Windows Phone"} in appropriate REs.
Go ahead and try it - if you have issues just send me word.
10x :)

**Comment by vinaynaidu** [comment]
Hi, submitted a pr: #33 but travis is failing due to some dependency. I'm at a new work place and haven't had a chance to setup any tools for minification etc yet, so used an online minify for the min.js. Let me know if/what I need to do, thanks.

**Comment by vinaynaidu** [comment]
Closed the issue as the pr was merged; feel free to reopen if something's amiss. Thanks!
