### ISSUE TITLE
Chromebook Pixel (2015) is considered 'mobile' and 'tablet'

### ISSUE THREAD

**Issue by codysherman** [srfrnk/ng-device-detector#35]
My Pixel is showing up as a mobile phone essentially, it should be considered a desktop.

browser: "chrome"
browser_version: "46.0.2490.52"
device: "chrome-book"
isDesktop: false
isMobile: true
isTablet: true
os: "chrome-os"
os_version: "unknown"

**Comment by dgoncalves1** [comment]
Probably based on the OS, not sure if the chromebook is considered a desktop imho

**Comment by codysherman** [comment]
Yeah, looking at the code, appears to these two lines incorrectly flagging it as mobile and tablet:
https://github.com/srfrnk/ng-device-detector/blob/master/ng-device-detector.js#L268
https://github.com/srfrnk/ng-device-detector/blob/master/ng-device-detector.js#L280

Chromebooks are in the form factor of laptops, and don't obey tablets/mobile rules such as not autoplaying video. Please switch Chromebooks to the correct reading of just 'isDesktop'.

**Comment by dgoncalves1** [comment]
I see, it's detecting the device correctly, just targetting at the wrong group, let's see what the author thinks.

**Comment by codysherman** [comment]
I have fixed the issue and submitted a pull request: https://github.com/srfrnk/ng-device-detector/pull/36

**Comment by dgoncalves1** [comment]
Outstanding, it has been merged, thanks!

**Comment by srfrnk** [comment]
:)
