### ISSUE TITLE
Does not work on Angular version 1.4.4 or 1.4.7

### ISSUE THREAD

**Issue by jakepens71** [srfrnk/ng-device-detector#37]
"ng.deviceDetector" can not be found when injecting it to my application.

I have tested this on both 1.4.4 and 1.4.7.

I have not tried any other versions.

**Comment by srfrnk** [comment]
can you create a plunker to demo this issue and attach a link to a comment here?

**Comment by jakepens71** [comment]
I did here: http://plnkr.co/edit/9Xz1gbjCwWo8lVQq9j16

I apologize if i am missing something, I am quite new to Angular JS. However, it seems that my variable works fine on the DOM when i remove "ng.deviceDetector".

**Comment by srfrnk** [comment]
No problems :) Glad you could get it to work :)
