### ISSUE TITLE
detect messenger browser

### ISSUE THREAD

**Issue by jakubkrizka** [srfrnk/ng-device-detector#39]
Is there any chance to detect messenger browser?
userAgent:

```json
"userAgent":"Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13B143 [FBAN/MessengerForiOS;FBAV/48.0.0.20.47;FBBV/17291106;FBDV/iPad2,5;FBMD/iPad;FBSN/iPhone OS;FBSV/9.1;FBSS/1; FBCR/;FBID/tablet;FBLC/cs_CZ;FBOP/1]"
```

**Comment by srfrnk** [comment]
Looks like you can add an entry for it and use 'FBAN/Messenger' in the
regex. Hopefully this will work to devices without IOS too.
If you do that - please remember to add a test for any such user agent use
cases.
10x.
