### ISSUE TITLE
Detect TV or Smart TV browser

### ISSUE THREAD

**Issue by FDiskas** [srfrnk/ng-device-detector#40]
The list of TVS User Agent
https://udger.com/resources/ua-list/device-detail?device=Smart%20TV

**Comment by srfrnk** [comment]
Feel free to add these.
You will need to add them to the 'DEVICES_RE' object , 'DEVICES' constant configuration, 'deviceInfo.device' array and optionally to the 'deviceInfo' - 'isDesktop' function.
Of course tests must be added per UA string.
Also version must be updated and minified version should be updated (these can be done easily using the grunt task within the project)
10x.
