### ISSUE TITLE
detect as desktop with BlackBerry PlayBook

### ISSUE THREAD

**Issue by xyuanX** [srfrnk/ng-device-detector#41]
I am testing this lib with chrome, if the device set to BlackBerry PlayBook (screen resolution 600 * 1024).

isDesktop() return true
isMobile() return false
isTablet() return false

get any idea why is that?

and get the same result for Nokia N9

**Comment by srfrnk** [comment]
Hi,

First - what's the user-agent string you're getting there? (you can see it in deviceDetector.raw.userAgent)
Second - what would you expect there? Would you consider it to be a tablet then?

10x,
Shahar.
