### ISSUE TITLE
Edge is not detected

### ISSUE THREAD

**Issue by intellix** [srfrnk/ng-device-detector#44]
Seems that Edge isn't detected and just returns browser-unknown. Not quite sure how we should be detecting it as the user-agent is a little bare. I don't think we need "browser-edge", since they just renamed IE and then marketed it as a brand new product... nothing changed in regards to support unless anyone can prove me wrong

**User agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64)

**Comment by srfrnk** [comment]
I'm gonna detect using this bare UA since I can see no other option.
It will not be very resilient to future releases of the browser though.
