### ISSUE TITLE
Chrome in iPad browser_version is "0"

### ISSUE THREAD

**Issue by nunofaria11** [srfrnk/ng-device-detector#45]
It seems `deviceDetector.browser_version` in Chrome + iPad always returns "0",´

Chrome 49.0.2623.73
iOS 9.2.1

**Comment by srfrnk** [comment]
Could you specify the exact UA string you're getting in this scenario?

**Comment by nunofaria11** [comment]
Oddly enough the UA string is the following (Chrome + iPad)
```
Mozilla/5.0 (iPad; CPU OS 9_2_1 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/49.0.2623.73 Mobile/13D15 Safari/601.1.46
```

**Comment by srfrnk** [comment]
i've added a verification case for the issue.
however it seems that the correct chrome version is returned.
please check to see that you are using the latest release (or use the latest commit)

**Comment by nunofaria11** [comment]
I updated to latest version and it is fixed - sorry for the inconvenience and thank you for your time :)
Closing this issue.

**Comment by srfrnk** [comment]
No problem - enjoy :)
