### ISSUE TITLE
Device vs. OS

### ISSUE THREAD

**Issue by alexg313** [srfrnk/ng-device-detector#47]
Thanks for putting this together. Pretty handy. Here's a potential improvement. 

My UserAgent string is: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"

And here's what deviceDetector finds: 
`browser: "chrome", browser_version: "49.0.2623.87", os: "mac", os_version: "mac-os-x-11", device: "unknown"`

Really, the OS should be "OSX" and the device should be "mac", instead of having an "unknown" device.

**Comment by srfrnk** [comment]
This is something new just recently added by @oheins.
Oliver can you please respond?

**Comment by srfrnk** [comment]
Is it still an issue?
