### ISSUE TITLE
Android Phones and Tablets

### ISSUE THREAD

**Issue by R-Kurbatovvakoms** [srfrnk/ng-device-detector#48]
Can we differ that devices somehow? In examples I've seen tablets don't have word Mobile in navigator.

**Comment by srfrnk** [comment]
There are separate 'isMobile' and 'isTablet' functions that you can use for that if I understand your question properly, isn't that enough?

**Comment by R-Kurbatovvakoms** [comment]
@srfrnk thanks for response. isTablet returns true only for iPad and Firefox OS devices and I mean distinction of Android tablets and Android phones. As I understand it's quite tricky thing and so results can't be stable as the main difference is resolution.

**Comment by srfrnk** [comment]
can you suggest another way of distinguishing tablets then?

**Comment by R-Kurbatovvakoms** [comment]
Like suggested here https://webmasters.googleblog.com/2011/03/mo-better-to-also-detect-mobile-user.html tablets don't have Mobile string in UA.

**Comment by srfrnk** [comment]
Maybe you implement your suggestion as an add-on thus not breaking the existing schema?
