### ISSUE TITLE
Can we make detect it is loaded from Iframe

### ISSUE THREAD

**Issue by Soe-Lynn-Htike** [srfrnk/ng-device-detector#49]

**Comment by srfrnk** [comment]
Can you suggest how to do that?

**Comment by Soe-Lynn-Htike** [comment]
i have no idea for that . i 'd been searching to check whether it is loaded from IFrame

function inIframe () {
    try {
        return window.self !== window.top;
    } catch (e) {
        return true;
    }
}

**Comment by srfrnk** [comment]
I'm not sure that such logic should really be part of the device detector.
However if you would like to add the code (and proper tests of course) I'd consider merging it.
