### ISSUE TITLE
Firefox 5.0 on iPad Air 2 detected as "Safari"

### ISSUE THREAD

**Issue by markyleong** [srfrnk/ng-device-detector#53]
Firefox 5.0 on iPad Air 2 is detected as "Safari".

The raw UA is:

`Mozilla/5.0 (iPad; CPU OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) FxiOS/5.0 Mobile/13G35 Safari/601.1.46`

**Comment by srfrnk** [comment]
Can you send the UA for safari on same device? Maybe I can find a way to disambiguate.

**Comment by markyleong** [comment]
Firefox:

`Mozilla/5.0 (iPad; CPU OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) FxiOS/6.0 Mobile/14C92 Safari/602.3.12`

Safari:

`Mozilla/5.0 (iPad; CPU OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0 Mobile/14C92 Safari/602.1`

**Comment by srfrnk** [comment]
please update the code directly from GitHub since the fix isn't included in latest release
