### ISSUE TITLE
Unable to load ng.deviceDetector module into my module 

### ISSUE THREAD

**Issue by ashwanikumar415** [srfrnk/ng-device-detector#56]
Hi , i have downloaded the     
"re-tree": "0.0.2",
"ng-device-detector": "3.0.1"  through package.json . They get successfully downloaded into node_modules directory . 
But now when the same module is loaded included in my module as a dependency like below :
var myApp = angular.module('myApp', [ require('ng-admin'),'base64','ngCookies', 'ngStorage', 'ng.deviceDetector']); 

i get below error : 
Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:modulerr] Failed to instantiate module ng.deviceDetector due to:
Error: [$injector:nomod] Module 'ng.deviceDetector' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

In index.html page, the modules are also loaded properly:
		<script type="text/javascript" src="vendorjs/re-tree/re-tree.js" charset="utf-8"></script>
		<script type="text/javascript" src="vendorjs/ng-device-detector/ng-device-detector.js" charset="utf-8"></script>

Could you please help me here ?

**Comment by srfrnk** [comment]
Hi @ashwanikumar415,

Can you check that you registered the module as a dependency in your module definition?
Can I see the code hosted somewhere?

**Comment by ashwanikumar415** [comment]
Apologies for late reply . Code is hosted presently at localhost itself .
For experiment i tried different library which is : "angular-bowser". i faced the similar issue .
But i could fix it with below lines : 

` require('angular-bowser');
var myApp = angular.module('myApp', [ require('ng-admin'),'base64','ngCookies', 'ngStorage', 'ng.deviceDetector']);`

i did not understand that even though the installed module was included in index.html page . Still had to do require('angular-bowser');

**Comment by srfrnk** [comment]
Gr8 @ashwanikumar415 - it's probably like I suspected.
You forgot to do the following step from the [Instalation Instructions](https://github.com/srfrnk/ng-device-detector):
- Add module to your app dependencies: ...angular.module("...", [..."ng.deviceDetector"...])...

Please make sure you went through all the steps described there.

**Comment by ashwanikumar415** [comment]
Unfortunately , as i mentioned in my above bug description . ng.deviceDetector module was included as a dependency
`var myApp = angular.module('myApp', [ require('ng-admin'),'base64','ngCookies', 'ngStorage', 'ng.deviceDetector']);`

**Comment by srfrnk** [comment]
If you can share the code or create a reproduction of the issue on [CodePen](http://codepen.io/) / [Plunker](https://plnkr.co/) (or equivalents) I can take a look.
As it is your description is not enough to make any conclusion.
The code works as far as I can see - take a look at the [demo plunker](http://plnkr.co/edit/urqMI1?p=preview) to see it at work.
