### ISSUE TITLE
CDN load

### ISSUE THREAD

**Issue by JoseGoncalves** [srfrnk/ng-device-detector#57]
Hi,

I've seen that this module is available at [cdnjs](https://cdnjs.com/libraries/ng-device-detector), nevertheless the [re-tree](https://github.com/srfrnk/re-tree) module, which is a dependency, can not be found in any CDN.
Can you push also [re-tree](https://github.com/srfrnk/re-tree)  to a CDN in order that we can load and use both modules via CDN?

Best regards,
José Gonçalves

**Comment by srfrnk** [comment]
Hi @JoseGoncalves,
I understand your issue.
I've created a [request for that at cdnjs](https://github.com/cdnjs/cdnjs/issues/10561)... if you'd like you can +1 - maybe it might get treated faster :)
I wish I could help more but I don't have any control over cdnjs.

**Comment by srfrnk** [comment]
On step closer - we have a pending [Pull request](https://github.com/cdnjs/cdnjs/pull/11106)

**Comment by srfrnk** [comment]
Got it :)

[re-tree on CDNJS](https://cdnjs.com/libraries/re-tree)
