### ISSUE TITLE
Request for app with ionic

### ISSUE THREAD

**Issue by vagostep** [srfrnk/ng-device-detector#59]
Hi, great module. I used in my web app and work excelent. But, i want compilate my webapp with Ionic to make an app. And i want to detect if the aplication is launcher via App o via the browser of the phone. Which variable i can used to detect this? Is possible detect this?

**Comment by srfrnk** [comment]
Hi @vagostep,

Can you run the app under both conditions and print the UserAgent string?
Send me both strings and maybe we can come up with a way to distinguish.

Shahar.

**Comment by vagostep** [comment]
Hi, the userAgent string that is print when i enter in the App (apk) is: 

"Mozilla/5.0 (Linux; U; Android 4.0.4; es-ve; LT22i Build/ 6.1.1.B.1.54) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/ 534.30"

and the userAgent string that is print when i enter via the phone browser (chrome) is: 

"Mozilla/5.0 (Linux; U; Android 4.0.4; es-ve; LT22i Build/ 6.1.1.B.1.54) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/ 534.30"

Is the same :$

**Comment by srfrnk** [comment]
The ng-device-detector uses the UserAgent to detect the device, os etc...
If there is no difference in the UA it will require some other way to detect.
Do you know of any other way to distinguish between them?
I don't know Ionic nor mobile enough to say if such a way exists but if you find it you can pretty easily incorporate it to the code - I could possibly help you there.

**Comment by vagostep** [comment]
@srfrnk Sure! Thanks for the answer. I'll investigated more and find a solution for my need. Have a good day!!!

**Comment by srfrnk** [comment]
@vagostep I talked to my wife and she says Ionic has a way to configure the UA to be visible to the application code. If you can add a unique ID into the UA we can make it become detectable.

Specifically we can add a general UA addon for ionic like that:
'Ionic/#.#.#'
Where #.#.# is the ionic version.

Does that sound reasonable?
Can you test that it's possible?

**Comment by vagostep** [comment]
@srfrnk Hi, i'll investigated that. But, I discovered that, when i'm the app, the variable $ window.document.URL starts with the string "file: ///" followed by a path that begins with "android_asset" whereas when entered by the browser, the string It starts with http: // or https: // I do not know if it is always standard, but it makes a lot of sense since the browser requests the page through that protocol, while the app loads it from its own directory. Do you think we could use this to detect if an app is being loaded locally or is a web page being requested?

**Comment by srfrnk** [comment]
The plug-in is designed to use UA to detect everything.
Introducing other sources is always possible but might break existing functionality and expose us to future problems - e.g. what if the UA is conflicting with what appears in UA etc..
The best course is using the UA to get what you need unless it is impossible for some reason.
I would even go further and sujest to the Ionic developers that they implement this UA as a standard since I guess many apps might benefit and they already implemented it internally as a feature so they did see the need. WDYT?

**Comment by vagostep** [comment]
@srfrnk 

![screenshot_2017-03-02-12-47-32](https://cloud.githubusercontent.com/assets/15386436/23521011/9ec49d64-ff53-11e6-9fe6-7b070e1ce9f5.png)

Hello, I added to the UA 'Cordova / X.X.X' with the version of Cordova to use at the end of the UA. Using <preference name = "AppendUserAgent" value = "" /> that adds to the end of the string the value you want. I think that's what you meant.

**Comment by srfrnk** [comment]
10x - that looks great.
I will add that tomorrow.
Plus I want to check how complex it would be to add a feature for custom detection.
This way you could inject UA values through Cordoba / Ionic / whatever and then use the plug-in to detect.

Shahar.

**Comment by vagostep** [comment]
@srfrnk yeah! thanks!! I'll be waiting to update :)

**Comment by srfrnk** [comment]
Please see latest release 4.0.0. Read the release comment to make sure it doesn't break stuff for you.
