### ISSUE TITLE
Cordova device detect not working always

### ISSUE THREAD

**Issue by vagostep** [srfrnk/ng-device-detector#61]
Hi, it's me again. I implement the change, and it works fine in some cases, when i enter via app/cordova. When the Browser is Safari, the deviceBrowser show me the cordova string, but when the Browser is Chrome, show the chrome string.

**Comment by srfrnk** [comment]
This is because I only detect cordova over safari.
Is chrome a valid case?
Which other browsers could appear within an Ionic/Cordova App?

**Comment by vagostep** [comment]
@srfrnk mmm I think, if appear the cordova string, always be detect over other browsers. do you think the same?

**Comment by srfrnk** [comment]
I am trying to minimize impact on existing users. A general override might be problematic. I will decide and implement on the weekend. You'd probably get an update on Sunday :)

**Comment by vagostep** [comment]
@srfrnk I understand you perfectly. Although, for the cordova string to appear, it must be set by the developer. You could indicate this condition of use in the instructions, so that it is known that the only way the app returns cordova, is because it was manually set. No??

**Comment by srfrnk** [comment]
I'm not saying that you're wrong but if some users alteady add cordova the same way they may get different result. I am trying to find the solution that minimizes the risk. I'll take a look at the code on the weekend and get your issue sorted out one way or another.

**Comment by srfrnk** [comment]
I added the Cordova override to chrome and firefox in addition to safari.
Other browsers seem to not be relevant.
Let's see if we need anything else.
