### ISSUE TITLE
Browser detecting Issue

### ISSUE THREAD

**Issue by Soe-Lynn-Htike** [srfrnk/ng-device-detector#62]
When I opened with ng-device-detector in chrome and list out all the things
it shows that safari value also sets true..

**Comment by srfrnk** [comment]
Can you please send me the UA from `deviceDetector.raw.userAgent`?

**Comment by Soe-Lynn-Htike** [comment]
![screenshot23](https://cloud.githubusercontent.com/assets/8434768/23693473/99d57542-040f-11e7-9cd5-1b34601690f5.png)
I attached screenshot. I opened  with chrome and in safari  one it shows true .

**Comment by srfrnk** [comment]
That's great but can you also add the UA as text so I can create a test for
it?

**Comment by Soe-Lynn-Htike** [comment]
deviceDetector.raw.browser.safari

**Comment by srfrnk** [comment]
I need the value of `deviceDetector.raw.userAgent` as text please.

**Comment by Soe-Lynn-Htike** [comment]
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.88 Safari/537.36

Sorry i didnt get what u mean. I am just a newbie :D

**Comment by srfrnk** [comment]
All fine man :)
I'll fix it on the weekend and let you know when it's out there.

**Comment by Soe-Lynn-Htike** [comment]
Thanks😀
