### ISSUE TITLE
deviceDetector return incorrect for UC Browser and Opera

### ISSUE THREAD

**Issue by webserveglobal** [srfrnk/ng-device-detector#68]
deviceDetector return incorrect browser for UC Browser and Opera browser, it returns Chrome.

**Comment by srfrnk** [comment]
Please supply the UA that produces the wrong results.

**Comment by webserveglobal** [comment]
**Opera** - Desktop
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36 OPR/46.0.2597.57"

**UC Browser** - Desktop
"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 UBrowser/6.1.2909.1403 Safari/537.36"

But for mobile it doesn't return any OPR/46.0.2597.57 for opera, UBrowser/6.1.2909.1403 for UC Browser

**Comment by srfrnk** [comment]
Can you explain what UBrowser is?
Also without UA strings for the mobile versions I could't test this issue and confirm/fix.
Can you please provide these? Preferably along with the expected return values.
