### ISSUE TITLE
Fail to start an unit test module with ng-device-detector dependencies

### ISSUE THREAD

**Issue by neuropaddy** [srfrnk/ng-device-detector#69]
I create a module with ng-device-detector dependency, and prepare a unit test to verify the module. But, I observed the unit test can not start properly. 

     // viewModule.ts
    var myApp = angular.module('viewModule', [ 'datatables', 'ng.deviceDetector', 'data-service']);
    // test-case
    describe('TestViewer', function (){
        beforeEach(module('datatables'));
        beforeEach(module('ng.deviceDetector'));
        beforeEach(module('data-service));

        //it-test-logic
    }

As I start the unit test, it returns **'TypeError: $controller is not a function'**, However, when I delete ' ng.deviceDetector' dependency, the test starts normal. 

     var myApp = angular.module('viewModule', [ 'datatables',  'data-service']);
    describe('TestViewer', function (){
        beforeEach(module('datatables'));
        beforeEach(module('data-service));    
        //it-test-logic
    }

The **"ng-device-detector": "4.0.3"** is already included in **package.json - 'devDependencies' and 'dependencies' setting**.

Do you know what is the missing piece to cause this problem. Your advice is appreciated. 
Many thanks.

**Comment by srfrnk** [comment]
Can you maybe create a [CodePen](https://codepen.io/) to demonstrate the issue so i can try to understand what's wrong?
