### ISSUE TITLE
Add Dependency to re-tree

### ISSUE THREAD

**Issue by Arany** [srfrnk/ng-device-detector#71]
Hi,

I needed some time to find out, that the re-tree library is actually a needed dependency for the deviceDetector to work. Without it, it does not load as a Provider.

It should be added in the readme and the package.json as a dependency.

**Comment by srfrnk** [comment]
Hi @Arany,

Sorry for the trouble. 
You are correct that re-tree is required.

If you check the [readme](https://github.com/srfrnk/ng-device-detector/blob/master/readme.md) you can see that it explain to add ```<script type="text/javascript" src=".../re-tree.js"></script>``` just before ```<script type="text/javascript" src=".../ng-device-detector.js"></script>```.
Also the [package.json](https://github.com/srfrnk/ng-device-detector/blob/master/package.json) file already contains the dependency ```"dependencies": {
    "re-tree": "~0.0.2"
  }```

I'd be more then happy to know if you think of any other way to make it clearer :)

**Comment by Arany** [comment]
Hmm, interesting. Because it did not install re-tree as a dependency via npm. Is the package maybe not updated?

**Comment by srfrnk** [comment]
Can you please try this and copy the output? (**assuming you're on some \*nix and have docker installed**)

Create a file named ```Dockerfile``` with this content (**create within an empty dir**):
```
FROM node
RUN npm init -y && npm i ng-device-detector
CMD ["bash","-c","ls -l /node_modules"]
```

Then cd to the new dir and run:
```
docker build -t ng-device-detector . && docker run ng-device-detector
```
10x.
