### ISSUE TITLE
Provide information from user provided UAs

### ISSUE THREAD

**Issue by bendem** [srfrnk/ng-device-detector#72]
Would it be possible to extract the logic populating `deviceInfo` into a re-usable service so that the developper is able to get information from other user agents then the one returned by `$window.navigator.userAgent`?

My use case is a profile page with a list of open sessions. Each open session has a UA, but I'd like to replace it with more user friendly icons.

Example of the code I'd love:

```html
<tr ng-repeat="(i, session) in sessions track by session.id">
    <!-- ....... -->
    <td><span class="device-icon" device-detector="session.userAgent" tooltip="session.userAgent"></span></td>
    <!-- ....... -->
</tr>
```

That way I could style `.device-icon.os-*` and `.device-icon.browser-*`.

**Comment by srfrnk** [comment]
Hi @bendem,
Pushed a propsal.
Can you please see if it helps your case?
You can see the newly added test for usage.
Waiting for your comments.

**Comment by bendem** [comment]
looks perfect, thanks a bunch for your time!

**Comment by srfrnk** [comment]
so i've thought about it and went a little further.
created a standalone ua parsing library.
might be more usable for your case?

[you can find it here](https://github.com/srfrnk/ua-device-detector)

next phase i'm going to remove the logic from `ng-device-detector` and use the new lib as a dependency.

would love to hear your thoughts :)

**Comment by bendem** [comment]
tbf, I only really used this because we didn't know how to write directives when we started the project. If I have to switch to using a library, I'll probably go with https://github.com/faisalman/ua-parser-js which is more mature.

**Comment by srfrnk** [comment]
sure - that's up to you - i'm just giving you another choice.
so can we close this issue?

**Comment by bendem** [comment]
Sure thing, thanks for your time!
