### ISSUE TITLE
Add android-phone and android-tablet to the device list by defining it from UA

### ISSUE THREAD

**Issue by chiefman1** [srfrnk/ng-device-detector#73]
You can define android-phone and android-tablet, using the presence of the word 'mobile' in User Agent for android devices:

[Google Webmaster](https://webmasters.googleblog.com/2011/03/mo-better-to-also-detect-mobile-user.html)

**Comment by srfrnk** [comment]
You can easily extend the library to add new custom detection rules using code such as this:

```javascript
deviceDetectorProvider.addCustom("Custom_UA_Entry", {
        and:["\\bCustom_UA_Entry\\b", {
            not:"\\bChrome\\b"
        }]
      });
```

Doesn't that cover your use case?

**Comment by chiefman1** [comment]
Yes, I guess. I'm closing the issue
