### ISSUE TITLE
chrome headless support

### ISSUE THREAD

**Issue by azachar** [srfrnk/ng-device-detector#74]
Hello, 
chrome when running with `--headless` is not recognized instead, I am getting safari.

Hope, it is an easy fix :)

Thanks for a great job!

Cheers,
Andrej

**Comment by srfrnk** [comment]
Hi Andrej,

Should be easy. Can you please send me the UA your'e getting?
It should show as a property of the device detector object.

Thx :)

**Comment by azachar** [comment]
Thanks for your reply!

You can figure it out from here:

https://udger.com/resources/ua-list/browser-detail?browser=Chrome%20Headless <https://udger.com/resources/ua-list/browser-detail?browser=Chrome%20Headless>


Cheers,
Andrej

**Comment by srfrnk** [comment]
https://github.com/srfrnk/ua-device-detector/issues/1

**Comment by srfrnk** [comment]
Please notice breaking changes. See [changelog](https://github.com/srfrnk/ng-device-detector/blob/master/changelog.md).

**Comment by azachar** [comment]
Great, Thank you!

Please, could you also tag the repository with v5.0.1 so it can be downloaded nicely.

Thanks,
Andrej

**Comment by srfrnk** [comment]
new tag and release added.
btw - you do know that you can use npm to manage versions right? (w/o needing the git tag/version update)

**Comment by azachar** [comment]
Thanks for your advice, sure I knew that. 

Could you please tell me what is the difference between 5.0.1 and 5.0.2 that is the latest in npm?

Thank you!

**Comment by srfrnk** [comment]
Looks like there's no diff.
Not sure why I bumped the version again.

**Comment by azachar** [comment]
Dear @srfrnk,

Perhaps you could do it like I did in my project using standard-version + automatic releasing to npm on travis, have a look at my plugin - https://github.com/azachar/protractor-screenshoter-plugin

It automatically generates changelogs and tags in the repo. All in sync :) 

Cheers,
Andrej

**Comment by srfrnk** [comment]
Thanks for the great suggestion @azachar !
Looking through your code I can see you're using the npm `standard-version` package as well as using travis npm deployment.
Am I missing anything?

**Comment by azachar** [comment]
That is it, plus git cz ( git commitizen )

**Comment by srfrnk** [comment]
Nice... so before pushing code you still need run `npm version`  or `npm release` right?
Anyway around that?

**Comment by azachar** [comment]
I just run `npm run release` and push tag and that is it.

**Comment by srfrnk** [comment]
ok gr8
10x for lmk - i will find some time to use these as well
