### ISSUE TITLE
ng-device-detector error in injection

### ISSUE THREAD

**Issue by fturiot** [srfrnk/ng-device-detector#75]
Actually probleme with ng-detector this day
certainly change crete error in angularjs
angular.js:38 Uncaught Error: [$injector:modulerr] 
yesterday good this day bad

**Comment by srfrnk** [comment]
Did you maybe update to version 5.x.x?
If so please so the [changelog](https://github.com/srfrnk/ng-device-detector/blob/master/changelog.md)
If not - can you please provide a [plunker](https://plnkr.co/) that show the problem?

**Comment by fturiot** [comment]
i have solve with cdn change 
regards
