### ISSUE TITLE
bower install failing on ua-device-detector 

### ISSUE THREAD

**Issue by vitalstatix** [srfrnk/ng-device-detector#76]
v5.0.1 has a dependency on     "ua-device-detector": "^1.0.1"    
This dependency does not exist. bower install for ng-device-detector fails with:

> bower install
bower ng-device-detector#master       not-cached https://github.com/srfrnk/ng-device-detector.git#master
bower ng-device-detector#master          resolve https://github.com/srfrnk/ng-device-detector.git#master
bower ng-device-detector#master         download https://github.com/srfrnk/ng-device-detector/archive/master.tar.gz
bower ng-device-detector#master          extract archive.tar.gz
bower ng-device-detector#master         resolved https://github.com/srfrnk/ng-device-detector.git#31e923cdfa
bower ua-device-detector#^1.0.1       not-cached https://github.com/srfrnk/ua-device-detector.git#^1.0.1
**bower ua-device-detector#^1.0.1          resolve https://github.com/srfrnk/ua-device-detector.git#^1.0.1**
bower re-tree#^0.0.2                      cached https://github.com/srfrnk/re-tree.git#0.0.2
bower re-tree#^0.0.2                    validate 0.0.2 against https://github.com/srfrnk/re-tree.git#^0.0.2
**bower ua-device-detector#^1.0.1     ENORESTARGET No tag found that was able to satisfy ^1.0.1**

Please update the ua-device-detector repo...

**Comment by srfrnk** [comment]
Hi @vitalstatix - can you please try again now?

**Comment by vitalstatix** [comment]
Works now.. 
`bower ua-device-detector#^1.0.1         download https://github.com/srfrnk/ua-device-detector/archive/v1.0.1.tar.gz`
Thanks for fixing it!

**Comment by jbanulso** [comment]
Shouldn't commit 31e923cdfa4327dc8bbc465dffbb7570f765bec6 be part of a patch release? Otherwise the dependencies are not automatically resolved...

**Comment by srfrnk** [comment]
Not sure I understand what you mean.
The major version was changed meaning that a breaking change was made.
Can you maybe describe the problem or show it with a plunker?

**Comment by jbanulso** [comment]
Sorry for the bad explanation. What I mean is that, if I install `ng-device-detector#^5.0.1`, it won't install the `ua-device-detector` package in my bower_components (it will only install the `re-tree` package, since it is specified in `ng-device-detector` bower dependencies).

Of course, by pointing `ng-device-detector`to the master branch instead of the release version all the dependencies will be installed, since it includes the changed bower.json in commit 31e923cdfa4327dc8bbc465dffbb7570f765bec6. Did I make any sense now? :)

**Comment by srfrnk** [comment]
@jbanulso - I can reproduce the issue now. Will fix on the weekend. Thx for LMK :)

**Comment by srfrnk** [comment]
@jbanulso - Can you please verify it's fixed?

**Comment by jbanulso** [comment]
@srfrnk great! Now it works as expected! 👍
