### ISSUE TITLE
deviceDetectorProvider.addCustom not working

### ISSUE THREAD

**Issue by simonemazzoni** [srfrnk/ng-device-detector#81]
Hello @srfrnk ,
I noticed that from version 5, the `deviceDetectorProvider.addCustom` function doesn't work anymore.
I noticed that the provider code [here](https://github.com/srfrnk/ng-device-detector/blob/v5.1.2/ng-device-detector.js#L24) doesn't set anymore the `deviceInfo.custom` property possibly causing the `addCustom` not working.

EDIT: version 4.0.3 has [this](https://github.com/srfrnk/ng-device-detector/blob/v4.0.3/ng-device-detector.js#L476) line of code which makes it work I guess.

Is this the problem or am I missing something?
Thanks

**Comment by srfrnk** [comment]
Thanks for the info @simonemazzoni 
This is weird. My first guess would be that it got lost in the refactoring when ua-device-detector was introduced.
I would've thought the tests should have triggered on this but obviously none did.
I will take a closer look - hopefully I'll have some spare time on the weekend.
Will update this issue.

**Comment by simonemazzoni** [comment]
Ok @srfrnk,
I can also have a closer look tomorrow in the morning and send a PR eventually.

**Comment by simonemazzoni** [comment]
@srfrnk I pull requested a fix for the issue.
Please have a look at it as soon as you can.
