### ISSUE TITLE
Feature Request: Add isAndroid() to deviceDetector Service

### ISSUE THREAD

**Issue by CatGuardian** [srfrnk/ng-device-detector#84]
I have a feature request to add an `isAndroid()` method to the deviceDetector service so I can do this:

```
if (deviceDetector.isAndroid()) {
}
```

I see that you have a deviceUtils service defined that has the `isAndroid()` method but why not just include it with the `deviceDetector` service directly?

Instead of posting another feature request on the ua-device-detector, I think you could implement the `isAndroid()` method on the ua-device-detector and then the way the code is written now, it looks like we would automatically get `isAndroid()` as part of the `deviceDetector` service.

**Comment by srfrnk** [comment]
Hi @CatGuardian - thanks for the input.
`deviceUtils` was designed as a high-level API and that's why it has this higher level functionality.
Are you proposing to merge these to API's?
Can you explain how the current design hinders you?

**Comment by CatGuardian** [comment]
Thanks for getting back to me.

Once I realized that `deviceUtils` was a different service I was ok. But at first, without looking at the source too hard, I had thought `isAndroid()` was already part of `deviceDetector` simply because the module was called `ng-device-detector` and I had wrongfully assumed it was all one bundled service.

I didn't see any harm in combining the two and so I made this request. Another way would be to provide better documentation in the Readme.

**Comment by srfrnk** [comment]
@CatGuardian - How would you change the docs to reflect that? Could you please create a PR so I can merge it?

**Comment by CatGuardian** [comment]
Right now the problem with the documentation is that it doesn't add anything about the DeviceUtils service. Here is how I would change the documentation:

* Add an 'Injecting DeviceUtils service in controller' line item similar to and near the 'Injecting DeviceDetector service in controller' line item.
* Add an entire 'deviceUtils' section similar to and right after the 'deviceDetectors' section. This section would outline the various methods it has and what they do.

Another way to do this would be to rework the documentation a little bit and have 2 big sections: the DeviceDetector section and the DeviceUtils section and then in those sections talk about injecting the respective service and then go over what they have and maybe some usage examples of those properties / methods.

Below is a copy of the markdown from the Readme of the parts I am referencing:






Injecting *DeviceDetector* service in controller
```js
angular.module('app').controller('Home', function($scope, deviceDetector){
  // Awesome stuff
});
```

To add classes, add directive like: `<div device-detector>`

### Setup

You can set custom detectors at the provider object.
The 
```javascript
angular.module('app', ["ng.deviceDetector"])
    .config(['deviceDetectorProvider', function(deviceDetectorProvider) {
      deviceDetectorProvider.addCustom("Custom_UA_Entry", {
        and:["\\bCustom_UA_Entry\\b", {
            not:"\\bChrome\\b"
        }]
      });
    }])
    
    .controller('Home', function($scope, deviceDetector) {
      // (true / false)
      $scope.customUAEntry = deviceDetector.custom["Custom_UA_Entry"];
    });
```

> Custom detectors will also be added as CSS classes with 'is-' prefix and encoded into css class name casing.

### deviceDetector service
Holds the following properties:
* raw : object : contains the raw values... for internal use mostly.
* os : string : name of current OS
* browser : string : name of current browser
* device : string : name of current device

**Comment by srfrnk** [comment]
I think it would be best to add the sections describing `DeviceUtils` to the README.
Could you create a PR for that so I can merge it?
